### ISSUE TITLE
Deplopyment serviceAccount.name incorrect reference

### ISSUE THREAD

**Issue by erikcw** [mogaal/helm-charts#17]
`serviceAccountName: {{ include "prometheus-yace-exporter.fullname" . }}` should be `serviceAccountName: {{ include "prometheus-yace-exporter.serviceAccountName" . }}`

https://github.com/mogaal/helm-charts/blob/45e58171e329246ce5596e0cf46ff9a44eb60127/prometheus-yace-exporter/templates/deployment.yaml#L96

**Comment by erikcw** [comment]
Looks like there is a PR for it already! https://github.com/mogaal/helm-charts/pull/16

**Comment by mogaal** [comment]
This should be fixed now, thanks @erikcw for helping out and very sorry for the delay.
