### ISSUE TITLE
[yace] servicemonitor is using targetPort instead of port

### ISSUE THREAD

**Issue by bschurig** [mogaal/helm-charts#3]
Hello, the configuration for the service monitor that the chart uses does not work properly. The servicemonitor is using `targetPort: 80`, which looks for a port exposed on a deployment instead of port, which uses a named port on a service. The targetPort needs to be updated to 5000 or swapped with `port: http` for the servicemonitor to work.

I'd be willing to make the change if you're open to a pull request.

**Comment by mogaal** [comment]
Hi @bschurig . If you can open a PR I'd really appreciate it. Let me know if you need any help.
