### ISSUE TITLE
helm url not reachable

### ISSUE THREAD

**Issue by TagadaPoe** [mogaal/helm-charts#6]
The URL in index.yaml, in the gh-pages branch, seems to be incorrect since yesterday. I am not able to helm-install prometheus-yace-exporter anymore.

It is currently set to 
```yaml
    urls:
    - https://mogaal.github.io/prometheus-yace-exporter-0.1.0.tgz
```
while previously it was:
```yaml
    urls:
    - prometheus-yace-exporter-0.1.0.tgz
```

**Comment by mogaal** [comment]
@TagadaPoe Just fixed, my bad. Updated the index.yaml with the wrong URL. Apologies.
